version: "3.8"
services:
  todo_list_app:
    container_name: todo_list_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - todo_list_db
    networks:
      - app_network

  todo_list_server:
    container_name: todo_list_server
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - todo_list_app
    tty: true
    environment:
      NGINX_FPM_HOST: todo_list_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  todo_list_db:
    container_name: todo_list_db
    image: mysql:8.0
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  todo_list_redis:
    container_name: todo_list_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

  pma:
    image: phpmyadmin:5.1
    restart: always
    networks:
      - app_network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - todo_list_db
    ports:
      - 8888:80

networks:
  app_network:
    driver: bridge
